# Generated by Django 6.0.3 on 2026-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_run",
            field=models.DateField(blank=True, null=True),
        ),
    ]
